[package]
name = "atrium-api"
version = "0.1.0"
edition = "2021"
authors = ["sugyan <sugi1982+github@gmail.com>"]

[dependencies]
async-trait = "0.1.68"
http = "0.2.9"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_urlencoded = "0.7.1"
