[package]
name = "atrium-xrpc"
version = "0.1.0"
edition = "2021"
authors = ["sugyan <sugi1982+github@gmail.com>"]

[dependencies]
atrium-api = { path = "../atrium-api" }
async-trait = "0.1.68"
http = "0.2.9"
reqwest = "0.11.16"
