[workspace]
members = [
    "atrium-api",
    "atrium-cli",
    "atrium-xrpc",
    "atrium-xrpc-client",
    "atrium-xrpc-server",
    "examples/concurrent",
    "examples/firehose",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.70"
repository = "https://github.com/sugyan/atrium"
license = "MIT"
keywords = ["atproto", "bluesky"]
