[package]
name = "atprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atprs-codegen = { path = "./atprs-codegen" }
clap = { version = "4.2.4", features = ["derive"] }

[workspace]
members = [
    "atprs-api",
    "atprs-cli",
    "atprs-codegen",
    "atprs-lex",
    "atprs-xrpc",
]
