[workspace]
members = [
    "atrium-api",
    "atrium-cli",
    "atrium-xrpc",
    "atrium-xrpc-client",
    "atrium-xrpc-server",
    "examples/concurrent",
    "examples/firehose",
]
resolver = "2"
