[package]
name = "atprs-xrpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atprs-api = { path = "../atprs-api" }
async-trait = "0.1.68"
chrono = "0.4.24"
http = "0.2.9"
reqwest = "0.11.16"
