[package]
name = "atprs-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atprs-lex = { path = "../atprs-lex" }
heck = "0.4.1"
serde_json = "1.0"
