[package]
name = "atrium-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atrium-lex = { path = "../atrium-lex" }
heck = "0.4.1"
itertools = "0.10.5"
serde_json = "1.0"
